minimum_pre_commit_version: "3.0"
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.11.2'
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.3
  hooks:
  - id: check-gitlab-ci
    files: .gitlab-ci.yml
#  - id: check-github-actions
#    files: .github/workflows/cicd.yaml
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.36.2
  hooks:
  - id: yamllint
    args: [-d, "{extends: relaxed, rules: {line-length: disable} }" ]
    verbose: true
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    # for args see https://mypy.readthedocs.io/en/stable/command_line.html
    args: [
      --no-strict-optional,
      --ignore-missing-imports,
      --allow-untyped-globals
    ]
    files: ^(src|tests)/.*\.py$
